export default [
  {
    id: 1,
    cardColor: '#EDF6EC',
    coordinate: 'Nº001',
    name: 'Bulbasaur',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: 'Venomous',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass-outline.png',
    avatar: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/bulbasaur.png',
    avatarHolderColor: '#63BC5A',
    favorite: true,
  },
  {
    id: 2,
    cardColor: '#EDF6EC',
    coordinate: 'Nº002',
    name: 'Ivysaur',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: 'Venomous',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass-outline.png',
    avatar: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/bulbasaur.png',
    avatarHolderColor: '#63BC5A',
    favorite: true,
  },
]