export default [
  {
    id: 1,
    cardColor: '#EDF6EC',
    coordinate: 'Nº001',
    name: 'Bulbasaur',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: 'Venomous',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/grass-outline.png',
    avatar: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/bulbasaur.png',
    avatarHolderColor: '#63BC5A',
    favorite: false,
  },
  {
    id: 2,
    cardColor: '#EDF6EC',
    coordinate: 'Nº002',
    name: 'Ivysaur',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: 'Venomous',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/grass-outline.png',
    avatar: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/ivysaur.png',
    avatarHolderColor: '#63BC5A',
    favorite: false,
  },
  {
    id: 3,
    cardColor: '#EDF6EC',
    coordinate: 'Nº003',
    name: 'Venusaur',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: 'Venomous',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/grass-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/venusaur.png?raw=true',
    avatarHolderColor: '#63BC5A',
    favorite: false,
  },
  {
    id: 4,
    cardColor: '#FCF3EB',
    coordinate: 'Nº004',
    name: 'Charmander',
    element: 'Fire',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fire.png',
    elementColor: '#FF9D55',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/fogo-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/charmander.png?raw=true',
    avatarHolderColor: '#FF9D55',
    favorite: false,
  },
  {
    id: 5,
    cardColor: '#FCF3EB',
    coordinate: 'Nº005',
    name: 'Charmeleon',
    element: 'Fire',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fire.png',
    elementColor: '#FF9D55',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/fogo-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/charmeleon.png?raw=true',
    avatarHolderColor: '#FF9D55',
    favorite: false,
  },
  {
    id: 5,
    cardColor: '#FCF3EB',
    coordinate: 'Nº006',
    name: 'Charizard',
    element: 'Fire',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fire.png',
    elementColor: '#FF9D55',
    type: 'Flying',
    typeImage: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/flying.png?raw=true',
    typeColor: '#89AAE3',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/fogo-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/charizard.png?raw=true',
    avatarHolderColor: '#FF9D55',
    favorite: false,
  },
  {
    id: 6,
    cardColor: '#EBF1F8',
    coordinate: 'Nº007',
    name: 'Squirtle',
    element: 'Water',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
    elementColor: '#5090D6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/squirtle.png?raw=true',
    avatarHolderColor: '#5090D6',
    favorite: false,
  },
  {
    id: 7,
    cardColor: '#EBF1F8',
    coordinate: 'Nº008',
    name: 'Wartortle',
    element: 'Water',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
    elementColor: '#5090D6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/wartotle.png?raw=true',
    avatarHolderColor: '#5090D6',
    favorite: false,
  },
  {
    id: 8,
    cardColor: '#EBF1F8',
    coordinate: 'Nº009',
    name: 'Blastoise',
    element: 'Water',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
    elementColor: '#5090D6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/blastoise.png?raw=true',
    avatarHolderColor: '#5090D6',
    favorite: false,
  },
  {
    id: 9,
    cardColor: '#F1F6E8',
    coordinate: 'Nº015',
    name: 'Beedrill',
    element: 'Insect',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/inseto.png',
    elementColor: '#91C12F',
    type: 'Venomous',
    typeImage: 'https://github.com/nonamelittlefox/Pokedex-App/blob/develop/public/images/venomous.png?raw=true',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/inseto-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/beedrill.png?raw=true',
    avatarHolderColor: '#91C12F',
    favorite: false,
  },
  {
    id: 10,
    cardColor: '#FBF8E9',
    coordinate: 'Nº025',
    name: 'Pikachu',
    element: 'Electric',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/electrico.png',
    elementColor: '#F4D23C',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/electronic-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/pikachu.png?raw=true',
    avatarHolderColor: '#F4D23C',
    favorite: false,
  },
  {
    id: 11,
    cardColor: '#FBF1FA',
    coordinate: 'Nº035',
    name: 'Clefairy',
    element: 'Fairy',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fada.png',
    elementColor: '#EC8FE6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fairy-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/clefairy.png?raw=true',
    avatarHolderColor: '#EC8FE6',
    favorite: false,
  },
  {
    id: 12,
    cardColor: '#F9EFEA',
    coordinate: 'Nº051',
    name: 'Dugtrio',
    element: 'Terrestrial',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/terrestre.png',
    elementColor: '#D97845',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/terrestrial-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/dugtrio.png?raw=true',
    avatarHolderColor: '#D97845',
    favorite: false,
  },
]


  // {
  //   id: ,
  //   cardColor: '#',
  //   coordinate: 'Nº007',
  //   name: '',
  //   element: '',
  //   elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
  //   elementColor: '#',
  //   type: '',
  //   typeImage: '',
  //   typeColor: '',
  //   elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
  //   avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/squirtle.png?raw=true',
  //   avatarHolderColor: '#',
  //   favorite: false,
  // },