export default [
  {
    id: 1,
    cardColor: '#EDF6EC',
    coordinate: 'Nº001',
    name: 'Bulbasaur',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: 'Venomous',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/grass-outline.png',
    avatar: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/bulbasaur.png',
    avatarHolderColor: '#63BC5A',
    favorite: false,
    gif: require('../../../public/images/info/bulbasaur_gif.gif'),
  },
  {
    id: 2,
    cardColor: '#EDF6EC',
    coordinate: 'Nº002',
    name: 'Ivysaur',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: 'Venomous',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/grass-outline.png',
    avatar: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/ivysaur.png',
    avatarHolderColor: '#63BC5A',
    favorite: false,
    gif: require('../../../public/images/info/ivysaur_gif.gif'),
  },
  {
    id: 3,
    cardColor: '#EDF6EC',
    coordinate: 'Nº003',
    name: 'Venusaur',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: 'Venomous',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/grass-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/venusaur.png?raw=true',
    avatarHolderColor: '#63BC5A',
    favorite: false,
    gif: require('../../../public/images/info/venusaur_gif.gif'),
  },
  {
    id: 4,
    cardColor: '#FCF3EB',
    coordinate: 'Nº004',
    name: 'Charmander',
    element: 'Fire',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fire.png',
    elementColor: '#FF9D55',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/fogo-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/charmander.png?raw=true',
    avatarHolderColor: '#FF9D55',
    favorite: false,
  },
  {
    id: 5,
    cardColor: '#FCF3EB',
    coordinate: 'Nº005',
    name: 'Charmeleon',
    element: 'Fire',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fire.png',
    elementColor: '#FF9D55',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/fogo-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/charmeleon.png?raw=true',
    avatarHolderColor: '#FF9D55',
    favorite: false,
  },
  {
    id: 5,
    cardColor: '#FCF3EB',
    coordinate: 'Nº006',
    name: 'Charizard',
    element: 'Fire',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fire.png',
    elementColor: '#FF9D55',
    type: 'Flying',
    typeImage: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/flying.png?raw=true',
    typeColor: '#89AAE3',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/master/public/images/fogo-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/charizard.png?raw=true',
    avatarHolderColor: '#FF9D55',
    favorite: false,
  },
  {
    id: 6,
    cardColor: '#EBF1F8',
    coordinate: 'Nº007',
    name: 'Squirtle',
    element: 'Water',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
    elementColor: '#5090D6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/squirtle.png?raw=true',
    avatarHolderColor: '#5090D6',
    favorite: false,
  },
  {
    id: 7,
    cardColor: '#EBF1F8',
    coordinate: 'Nº008',
    name: 'Wartortle',
    element: 'Water',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
    elementColor: '#5090D6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/wartotle.png?raw=true',
    avatarHolderColor: '#5090D6',
    favorite: false,
  },
  {
    id: 8,
    cardColor: '#EBF1F8',
    coordinate: 'Nº009',
    name: 'Blastoise',
    element: 'Water',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
    elementColor: '#5090D6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/blastoise.png?raw=true',
    avatarHolderColor: '#5090D6',
    favorite: false,
  },
  {
    id: 9,
    cardColor: '#F1F6E8',
    coordinate: 'Nº015',
    name: 'Beedrill',
    element: 'Insect',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/inseto.png',
    elementColor: '#91C12F',
    type: 'Venomous',
    typeImage: 'https://github.com/nonamelittlefox/Pokedex-App/blob/develop/public/images/venomous.png?raw=true',
    typeColor: '#B567CE',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/inseto-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/beedrill.png?raw=true',
    avatarHolderColor: '#91C12F',
    favorite: false,
  },
  {
    id: 10,
    cardColor: '#FBF8E9',
    coordinate: 'Nº025',
    name: 'Pikachu',
    element: 'Electric',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/electrico.png',
    elementColor: '#F4D23C',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/electronic-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/pikachu.png?raw=true',
    avatarHolderColor: '#F4D23C',
    favorite: false,
  },
  {
    id: 11,
    cardColor: '#FBF1FA',
    coordinate: 'Nº035',
    name: 'Clefairy',
    element: 'Fairy',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fada.png',
    elementColor: '#EC8FE6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fairy-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/clefairy.png?raw=true',
    avatarHolderColor: '#EC8FE6',
    favorite: false,
  },
  {
    id: 12,
    cardColor: '#F9EFEA',
    coordinate: 'Nº051',
    name: 'Dugtrio',
    element: 'Terrestrial',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/terrestrial.png',
    elementColor: '#D97845',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/terrestrial-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/dugtrio.png?raw=true',
    avatarHolderColor: '#D97845',
    favorite: false,
  },
  {
    id: 13,
    cardColor: '#F7F5F1',
    coordinate: 'Nº095',
    name: 'Onix',
    element: 'Stone',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/pedra.png',
    elementColor: '#C5B78C',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/stone-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/onix.png?raw=true',
    avatarHolderColor: '#C5B78C',
    favorite: false,
  },
  {
    id: 14,
    cardColor: '#F1F2F3',
    coordinate: 'Nº108',
    name: 'Lickitung',
    element: 'Normal',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/normal.png',
    elementColor: '#919AA2',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/normal-outnline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/lickitung.png?raw=true',
    avatarHolderColor: '#919AA2',
    favorite: false,
  },
  {
    id: 15,
    cardColor: '#F5EDF8',
    coordinate: 'Nº109',
    name: 'Koffing',
    element: 'Venomous',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous.png',
    elementColor: '#B567CE',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/venomous-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/knoffing.png?raw=true',
    avatarHolderColor: '#B567CE',
    favorite: false,
  },
  {
    id: 16,
    cardColor: '#FCEEEF',
    coordinate: 'Nº151',
    name: 'Mew',
    element: 'Psychic',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/psiquico.png',
    elementColor: '#FA7179',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/psychic-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/mew.png?raw=true',
    avatarHolderColor: '#FA7179',
    favorite: false,
  },
  {
    id: 17,
    cardColor: '#EBF1F8',
    coordinate: 'Nº245',
    name: 'Suicune',
    element: 'Water',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
    elementColor: '#5090D6',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/suicune.png?raw=true',
    avatarHolderColor: '#5090D6',
    favorite: false,
  },
  {
    id: 18,
    cardColor: '#ECF1F3',
    coordinate: 'Nº306',
    name: 'Aggron',
    element: 'Metal',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/metal.png',
    elementColor: '#5A8EA2',
    type: 'Terrestrial',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/terrestrial.png',
    typeColor: '#D97845',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/metal-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/aggron.png?raw=true',
    avatarHolderColor: '#5A8EA2',
    favorite: false,
  },
  {
    id: 19,
    cardColor: '#E4EEF6',
    coordinate: 'Nº384',
    name: 'Rayquaza',
    element: 'Dragon',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/dragao.png',
    elementColor: '#0B6DC3',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/dragao-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/rayquaza.png?raw=true',
    avatarHolderColor: '#0B6DC3',
    favorite: false,
  },
  {
    id: 20,
    cardColor: '#F8E9EE',
    coordinate: 'Nº448',
    name: 'Lucario',
    element: 'Wrestler',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/lutador.png',
    elementColor: '#CE416B',
    type: 'Metal',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/metal.png',
    typeColor: '#5A8EA2',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fighter-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/lucario.png?raw=true',
    avatarHolderColor: '#CE416B',
    favorite: false,
  },
  {
    id: 21,
    cardColor: '#EDF6EC',
    coordinate: 'Nº497',
    name: 'Serperior',
    element: 'Grass',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass.png',
    elementColor: '#63BC5A',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/grass-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/serperior.png?raw=true',
    avatarHolderColor: '#63BC5A',
    favorite: false,
  },
  {
    id: 22,
    cardColor: '#ECEBED',
    coordinate: 'Nº571',
    name: 'Zoroark',
    element: 'Nocturnal',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/noturno.png',
    elementColor: '#5A5465',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/nocturnal-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/zoroark.png?raw=true',
    avatarHolderColor: '#5A5465',
    favorite: false,
  },
  {
    id: 23,
    cardColor: '#EBEDF4',
    coordinate: 'Nº609',
    name: 'Chandelure',
    element: 'Phantom',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fantasma.png',
    elementColor: '#5269AD',
    type: 'Fire',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/fire.png',
    typeColor: '#FF9D55',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/ghost-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/chandelure.png?raw=true',
    avatarHolderColor: '#5269AD',
    favorite: false,
  },
  {
    id: 24,
    cardColor: '#F1FBF9',
    coordinate: 'Nº613',
    name: 'Cubchoo',
    element: 'Frost',
    elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/gelo.png',
    elementColor: '#73CEC0',
    type: '',
    typeImage: '',
    typeColor: '',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/ice-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/cubchoo.png?raw=true',
    avatarHolderColor: '#73CEC0',
    favorite: false,
  },
  {
    id: 25,
    cardColor: '#F1F4FA',
    coordinate: 'Nº733',
    name: 'Toucannon',
    element: 'Flying',
    elementImage: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/flying.png?raw=true',
    elementColor: '#89AAE3',
    type: 'Normal',
    typeImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/normal.png',
    typeColor: '#919AA2',
    elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/flying-outline.png',
    avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/toucannon.png?raw=true',
    avatarHolderColor: '#89AAE3',
    favorite: false,
  },
]


  // {
  //   id: ,
  //   cardColor: '#',
  //   coordinate: 'Nº007',
  //   name: '',
  //   element: '',
  //   elementImage: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua.png',
  //   elementColor: '#',
  //   type: '',
  //   typeImage: '',
  //   typeColor: '',
  //   elementBackground: 'https://raw.githubusercontent.com/nonamelittlefox/Pokedex-App/develop/public/images/aqua-outline.png',
  //   avatar: 'https://github.com/nonamelittlefox/Pokedex-App/blob/master/public/images/squirtle.png?raw=true',
  //   avatarHolderColor: '#',
  //   favorite: false,
  // },